line_width: 79
tab_size: 2
max_subgroups_hwrap: 2
max_pargs_hwrap: 6
separate_ctrl_name_with_space: true
separate_fn_name_with_space: true
dangle_parens: true
dangle_align: prefix
min_prefix_chars: 4
max_prefix_chars: 10
max_lines_hwrap: 1
line_ending: unix
command_case: upper
keyword_case: upper
additional_commands:
  cpmaddpackage:
    kwargs:
      NAME: '*'
      GITHUB_REPOSITORY: '*'
      GITLAB_REPOSITORY: '*'
      GIT_TAG: '*'
      DOWNLOAD_ONLY: '*'
      VERSION: '*'
      OPTIONS: '*'
      SOURCE_SUBDIR: '*'
      URL: '*'
      BUILD_COMMAND: '*'
      BUILD_IN_SOURCE: '*'
      CONFIGURE_COMMAND: '*'
      URL_HASH: '*'
  externalproject_add:
    kwargs:
      DOWNLOAD_COMMAND: '*'
      BUILD_IN_SOURCE: '*'
      SOURCE_DIR: '*'
      BINARY_DIR: '*'
      BUILD_COMMAND: '*'
      INSTALL_COMMAND: '*'
      DEPENDS: '*'
      CONFIGURE_COMMAND: 2
      SOURCE_SUBDIR: '*'
      CMAKE_ARGS: '2'
      CMAKE_CACHE_ARGS: '2'
      EXCLUDE_FROM_ALL: '*'
      COMMAND: '*'
      STEP_TARGETS: '*'
      BUILD_BYPRODUCTS: '*'
always_wrap: []
enable_sort: true
autosort: true
hashruler_min_length: 10
per_command: {}
layout_passes: {}
bullet_char: '*'
enum_char: .
enable_markup: true
first_comment_is_literal: false
literal_comment_pattern: null
fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$
ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$
canonicalize_hashrulers: true
emit_byteorder_mark: false
input_encoding: utf-8
output_encoding: utf-8
