default:
  image: mondaic/sed:pyrtdd
  before_script:
    - export PATH=/home/user/.miniconda/envs/scrtdd/bin:${PATH}

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1

stages:
  - build-cpm-cache
  - build-test

build-cpm-cache:
  stage: build-cpm-cache
  script:
    - mkdir -p /home/user/build && cd $_ && pwd && ls -a
    - cmake -S ${CI_PROJECT_DIR} -DCPM_SOURCE_CACHE:PATH=${CI_PROJECT_DIR}/.cache/cpm
  cache:
    - key: cpm
    - paths: [.cache/cpm]
    - policy: pull-push
  when: manual

.cache-config: &cache-config
  cache:
    - key: cpm
    - paths: [.cache/cpm]
    - policy: pull

gcc-12:
  stage: build-test
  script:
    - CC=gcc-12
      CXX=g++-12
      SKBUILD_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER:STRING=gcc-12 -DCMAKE_CXX_COMPILER:STRING=g++-12 -DCPM_SOURCE_CACHE:PATH=$CI_PROJECT_DIR/.cache/cpm"
      SKBUILD_BUILD_OPTIONS="-v"
      pip install -v .
    - pytest -v
  <<: *cache-config
  needs: []

clang-14:
  stage: build-test
  script:
    - CC=clang-14
      CXX=clang++-14
      SKBUILD_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER:STRING=clang-14 -DCMAKE_CXX_COMPILER:STRING=clang++-14 -DCPM_SOURCE_CACHE:PATH=$CI_PROJECT_DIR/.cache/cpm"
      SKBUILD_BUILD_OPTIONS="-v"
      pip install -v .
    - pytest -v
  <<: *cache-config
  needs: []
