[build-system]
requires = [
    "cmake>=3.22",
    "pybind11~=2.9.2",
    "scikit-build>=0.15.0",
    "setuptools>=42",
    "wheel",
    "ninja; platform_system!='Windows'",
]

build-backend = "setuptools.build_meta"